### ISSUE TITLE
Member table columns still display sort icons when column is hidden in mobile view

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/daohaus-monorepo#837]
### Feature

admin ui

### App

- [X] [Admin](https://admin.daohaus.fun)
- [ ] [Summon](https://summon.daohaus.fun)
- [ ] [Hub](https://hub.daohaus.fun)
- [ ] [Toolbox](https://toolbox.daohaus.fun/)

### Expected Behavior

sort icons should disappear when the column content does.

### Actual Behavior

they don't

### Steps to Reproduce

go to the members page and shrink the screen width

### Screenshots and Context

![Screenshot from 2022-09-15 13-05-19](https://user-images.githubusercontent.com/6923345/190488436-1dfcdf63-a1d8-41dc-b283-01658a4c47d6.png)

**Comment by jordanlesich** [comment]
@earth2travis 

I think I already fixed this

**Comment by earth2travis** [comment]
@jordanlesich still an issue on https://admin.daohaus.fun/#/molochv3/0x5/0x5e0158adb4d5ccf34736aa5e3d25b23ce41c131d/members unless your updates have not been deployed to the subdomain

<img width="456" alt="image" src="https://user-images.githubusercontent.com/522182/192618872-5b195e39-518d-4ac9-82a0-6cd4c9a89bdb.png">

**Comment by jordanlesich** [comment]
Ah, the media queries weren't synced for the middle breakpoints. Got it now.

**Comment by jordanlesich** [comment]
Also, fixed the table header text breaking.
